### ISSUE TITLE
Cannot load PDF file that contains non-ascii characters in file path on Windows

### ISSUE THREAD

**Issue by khanhtd36** [YinlinHu/pypdfium#8] opened 2021-10-16 22:44 UTC
OS: Windows 10 x64 21H1 (build 19043.1288)
Python: CPython 3.6.8 x64
Library version: pypdfium==0.0.15

Input pdf file path that contains non-ascii character (eg. tênfilechứakýtựđặcbiệt.pdf) cannot be read by the library.

```python
doc = pdfium.FPDF_LoadDocument('tênfilechứakýtựnonasscii.pdf', None)
page_count = pdfium.FPDF_GetPageCount(doc)  # page_count = 0 !?
```

**Comment by adam-huganir** [comment] 2021-10-21 13:33
I can't authoritatively say this is not an issue with this pypdfium, since the library bindings are outside of my normal wheelhouse, but since it looks like that is a direct interface to the `pdfium` library itself (as in the google library) I suspect there is nothing that can be done on this side without making this project more than just an interface to the pdfium binary.

The related source that will show pypdfium is just forwarding the info to the linked library rather than doing its own transformations: https://github.com/YinlinHu/pypdfium/blob/5807c8aac5cc16ce88fe92b0f28cac733bb3e1df/pypdfium/pypdfium.py#L1170

I have run into issues with libraries not supporting filenames before, and the best option I have come up with before is just to rename and open and then rename the output or possibly use `FPDF_LoadMemDocument64`, to load from the doc you would manually `open("tênfilechứakýtựnonasscii.pdf", "rb")` in python

API Docs for `pdfium` `FPDF_LoadMemDocument` function here:
https://developers.foxit.com/resources/pdf-sdk/c_api_reference_pdfium/group___f_p_d_f_i_u_m.html#gafc1bfd72af5ccb5d6b9112c50fe90834

**Comment by mara004** [comment] 2021-10-21 20:07
With pypdfium-reboot, at least on Linux Ubuntu I have no issues with filenames that contain non-ascii characters.

Of course it could be a Windows-only issue, but I'm not entirely certain whether special characters are truly the cause here.

A different possible reason might be that (apparently) @khanhtd36 used a relative file path, though as far as I can tell only absolute paths work. However, when PDFium can't find the file, it does not raise an Exception as you would expect, but instead it may either silently create an empty document or return None. Both leads to page count being zero.

Further input from the reporter would be helpful to clarify the reason. The main point that would need to be confirmed is whether reading the file works correctly when it is renamed to an ascii-only name.

**Comment by mara004** [comment] 2021-10-23 16:07
Confirmed this is a platform-specific issue, see https://github.com/mara004/pypdfium-reboot/issues/1#issuecomment-950174027

**Comment by khanhtd36** [comment] 2021-10-27 11:04
Thank you, using FPDF_LoadMemDocument I can now load any pdf file without error.

And here is my code for someone who need it.

```python
def _load_pdf(pdf_filepath, password=None):
  # return None if file not found
  # return pdfium.FPDF_LoadDocument(f'{pdf_filepath}', password)

  try:
    with open(f'{pdf_filepath}', 'rb') as pdf_file:
      pdf_content_buff = pdf_file.read()
      buff_size = len(pdf_content_buff)
      return pdfium.FPDF_LoadMemDocument(pdf_content_buff, buff_size, password)
  except FileNotFoundError:
    return None
```

**Comment by mara004** [comment] 2022-09-08 14:57
This is now fixed upstream. pypdfium obviously doesn't get updates anymore, but pypdfium2 wheels contain the fix since quite some time. pypdfium2 now also properly offers other loading strategies in the support mode, including `FPDF_LoadMemDocument()` and `FPDF_LoadCustomDocument()`.

Important note: the `FPDF_LoadMemDocument()` code as shown above is not complete; callers need to ensure that the buffer object stays referenced, otherwise it may be garbage collected while PDFium still assumes the memory to contain the PDF. This may lead to random content errors or segmentation faults.

**Closed as completed by mara004** 2022-09-08 14:57 UTC
